### ISSUE TITLE
Git Seems to Interfere with Running Example

### ISSUE THREAD

**Issue by craig-riecke** [CU-CloudCollab/beanstalk-docker-example#1]
I'm following the steps in the README.md, but every time I get to `eb create example-test`, it throws errors referring to subnet-7704a001, which is present in the pristine copy of `example.config`.  But I had made all the changes there so the references are to our VPC, subnets, file system and security groups.  The smoking gun seems to be the message:

```
WARNING: You have uncommitted changes.
```

It seems that `eb create example-test` might be reading the Git repo information and grabbing the files from Master and deploying those, rather than the ones in my sandbox.

**Comment by paul-e-allen** [comment]
Yes, it’s a “feature” of the “eb deploy” command that it only looks at locally committed changes. You can use “eb deploy --staged" to deploy changes that are staged in git (i.e., “git add”ed) but not committed. As far as I know there is no way to get “eb deploy” to pay attention to unstaged changes.

-Paul

**Comment by craig-riecke** [comment]
Ah, thanks!  That was unclear to me from the README and the Elastic Beanstalk documentation (at least the 0.05% of it I read 😄 )  Do you mind if I submit a pull request with the changes to README.md?

**Comment by paul-e-allen** [comment]
Yes, please do. That would be great.

**Comment by craig-riecke** [comment]
I might be hijacking my own issue here, but ... I'm getting a little further, but now the `eb create example-test` dies with:

```
[Instance: i-46e0cbd8] Command failed on instance. Return code: 127 Output: /tmp/mount-efs.sh: line 17: service: command not found. command 020-mount-efs in .ebextensions/example.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
```

Which is weird because the `mount` command above it works, but the `service` command doesn't.  Am not sure what to check for ..

**Comment by craig-riecke** [comment]
NM.  I changed the line in the script to:

```
/usr/sbin/service docker restart
```

And it worked great.  I'll submit that change as part of the pull request.
